package org.emdev.common.log;

import android.annotation.SuppressLint;
import android.os.Build;

import org.emdev.BaseDroidApp;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.lang.Thread.UncaughtExceptionHandler;
import java.text.SimpleDateFormat;
import java.util.Date;

class EmergencyHandler implements UncaughtExceptionHandler {
    private final UncaughtExceptionHandler system;

    EmergencyHandler() {
        system = Thread.getDefaultUncaughtExceptionHandler();
        Thread.setDefaultUncaughtExceptionHandler(this);
    }

    @Override
    public void uncaughtException(final Thread thread, final Throwable ex) {
        processException(ex);
    }

    void processException(final Throwable ex) {
        @SuppressLint("SimpleDateFormat")
        final File file = new File(LogManager.LOG_STORAGE,
                BaseDroidApp.APP_PACKAGE + "." +
                     BaseDroidApp.APP_VERSION_NAME + "." +
                     new SimpleDateFormat("yyyyMMdd.HHmmss").format(new Date()) +
                     ".stacktrace");

        try (PrintWriter writer = new PrintWriter(file)) {
            writer.print(
                    "Application information:\n\n" +
                    "This file was generated by the " +
                    BaseDroidApp.APP_PACKAGE + "." + BaseDroidApp.APP_VERSION_NAME + "(" + BaseDroidApp.APP_VERSION_CODE + ")\n\n" +
                    "Device information:\n\n" +
                    "VERSION     : " + Build.VERSION.SDK_INT + "\n" +
                    "BOARD       : " + Build.BOARD + "\n" +
                    "BRAND       : " + Build.BRAND + "\n" +
                    "CPU_ABI     : " + BaseDroidApp.BUILD_PROPS.getProperty("ro.product.cpu.abi") + "\n" +
                    "CPU_ABI2    : " + BaseDroidApp.BUILD_PROPS.getProperty("ro.product.cpu.abi2") + "\n" +
                    "DEVICE      : " + Build.DEVICE + "\n" +
                    "DISPLAY     : " + Build.DISPLAY + "\n" +
                    "FINGERPRINT : " + Build.FINGERPRINT + "\n" +
                    "ID          : " + Build.ID + "\n" +
                    "MANUFACTURER: " + BaseDroidApp.BUILD_PROPS.getProperty("ro.product.manufacturer") + "\n" +
                    "MODEL       : " + Build.MODEL + "\n" +
                    "PRODUCT     : " + Build.PRODUCT + "\n\n" +
                    "Error information:\n\n");
            ex.printStackTrace(writer);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
